version: '3.1'

services:
  database:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./init.sql:/data/application/init.sql
      - springboot-service:/var/lib/mysql

volumes:
  springboot-service:
