# Server
server:
  port: 8080
  servlet:
    context-path: /robotic-hoover

spring:
  application:
    name: robotic-hoover-api
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/robotichoover?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: root
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1